// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbA3VPKlkfJXw27L_J1x5VbfxeqmjdR5o',
    appId: '1:232728961679:web:e53211fff778ab61b446fa',
    messagingSenderId: '232728961679',
    projectId: 'simplecloudnotifier-ea7ef',
    authDomain: 'simplecloudnotifier-ea7ef.firebaseapp.com',
    databaseURL: 'https://simplecloudnotifier-ea7ef.firebaseio.com',
    storageBucket: 'simplecloudnotifier-ea7ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBasR6JLAjM5Ut0rPb0euE_9DdDoTkcvKQ',
    appId: '1:232728961679:android:23c75317f79601c9',
    messagingSenderId: '232728961679',
    projectId: 'simplecloudnotifier-ea7ef',
    databaseURL: 'https://simplecloudnotifier-ea7ef.firebaseio.com',
    storageBucket: 'simplecloudnotifier-ea7ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJpUsV4ApJfQPcSDpPj2CkzNyS8093A8s',
    appId: '1:232728961679:ios:85155ba52c4f3311b446fa',
    messagingSenderId: '232728961679',
    projectId: 'simplecloudnotifier-ea7ef',
    databaseURL: 'https://simplecloudnotifier-ea7ef.firebaseio.com',
    storageBucket: 'simplecloudnotifier-ea7ef.appspot.com',
    androidClientId: '232728961679-o7gig6f684mp1l1ok7719v3jf3csejc1.apps.googleusercontent.com',
    iosBundleId: 'com.blackforestbytes.simplecloudnotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJpUsV4ApJfQPcSDpPj2CkzNyS8093A8s',
    appId: '1:232728961679:ios:85155ba52c4f3311b446fa',
    messagingSenderId: '232728961679',
    projectId: 'simplecloudnotifier-ea7ef',
    databaseURL: 'https://simplecloudnotifier-ea7ef.firebaseio.com',
    storageBucket: 'simplecloudnotifier-ea7ef.appspot.com',
    androidClientId: '232728961679-o7gig6f684mp1l1ok7719v3jf3csejc1.apps.googleusercontent.com',
    iosBundleId: 'com.blackforestbytes.simplecloudnotifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbA3VPKlkfJXw27L_J1x5VbfxeqmjdR5o',
    appId: '1:232728961679:web:6e8235651da6241eb446fa',
    messagingSenderId: '232728961679',
    projectId: 'simplecloudnotifier-ea7ef',
    authDomain: 'simplecloudnotifier-ea7ef.firebaseapp.com',
    databaseURL: 'https://simplecloudnotifier-ea7ef.firebaseio.com',
    storageBucket: 'simplecloudnotifier-ea7ef.appspot.com',
  );

}