
include: 
 - package:lints/recommended.yaml
 - package:flutter_lints/flutter.yaml

linter:
  
  
  rules:
    always_use_package_imports: true,
    avoid_empty_else: true,
    avoid_returning_null_for_future: true,
    avoid_type_to_string: true,
    avoid_types_as_parameter_names: true,
    avoid_web_libraries_in_flutter: true,
    collection_methods_unrelated_type: true,
    discarded_futures: true,
    empty_statements: true,
    hash_and_equals: true,
    implicit_reopen: true,
    invalid_case_patterns: true,
    invariant_booleans: true,
    no_duplicate_case_values: true,
    no_logic_in_create_state: true,
    no_self_assignments: true,
    no_wildcard_variable_uses: true,
    prefer_void_to_null: true,
    unnecessary_statements: true,
    valid_regexps: true,
    always_declare_return_types: true,
    always_put_control_body_on_new_line: true,
    always_specify_types: true,
    annotate_overrides: true,
    annotate_redeclares: true,
    avoid_annotating_with_dynamic: true,
    avoid_function_literals_in_foreach_calls: true,
    avoid_init_to_null: true,
    avoid_null_checks_in_equality_operators: true,
    avoid_renaming_method_parameters: true,
    avoid_return_types_on_setters: true,
    avoid_returning_null: true,
    avoid_returning_null_for_void: true,
    avoid_returning_this: true,
    avoid_shadowing_type_parameters: true,
    avoid_single_cascade_in_expression_statements: true,
    avoid_unnecessary_containers: true,
    avoid_unused_constructor_parameters: true,
    avoid_void_async: true,
    await_only_futures: true,
    camel_case_extensions: true,
    camel_case_types: true,
    cast_nullable_to_non_nullable: true,
    constant_identifier_names: true,
    empty_catches: true,
    eol_at_end_of_file: true,
    exhaustive_cases: true,
    file_names: true,
    no_literal_bool_comparisons: true,
    null_check_on_nullable_type_parameter: true,
    null_closures: true,
    overridden_fields: true,
    prefer_adjacent_string_concatenation: true,
    prefer_collection_literals: true,
    prefer_conditional_assignment: true,
    prefer_const_constructors: true,
    prefer_const_constructors_in_immutables: true,
    prefer_const_declarations: true,
    prefer_const_literals_to_create_immutables: true,
    prefer_contains: true,
    prefer_final_fields: true,
    prefer_for_elements_to_map_fromIterable: true,
    prefer_function_declarations_over_variables: true,
    prefer_generic_function_type_aliases: true,
    prefer_if_null_operators: true,
    prefer_initializing_formals: true,
    prefer_inlined_adds: true,
    prefer_interpolation_to_compose_strings: true,
    prefer_is_empty: true,
    prefer_is_not_empty: true,
    prefer_is_not_operator: true,
    prefer_iterable_whereType: true,
    prefer_null_aware_operators: true,
    prefer_spread_collections: true,
    prefer_typing_uninitialized_variables: true,
    provide_deprecation_message: true,
    recursive_getters: true,
    sized_box_for_whitespace: true,
    type_init_formals: true,
    type_literal_in_constant_pattern: true,
    unnecessary_const: true,
    unnecessary_constructor_name: true,
    unnecessary_getters_setters: true,
    unnecessary_late: true,
    unnecessary_new: true,
    unnecessary_null_aware_assignments: true,
    unnecessary_null_in_if_null_operators: true,
    unnecessary_nullable_for_final_variable_declarations: true,
    unnecessary_overrides: true,
    unnecessary_string_escapes: true,
    unnecessary_string_interpolations: true,
    unnecessary_this: true,
    unnecessary_to_list_in_spreads: true,
    use_full_hex_values_for_flutter_colors: true,
    use_function_type_syntax_for_parameters: true,
    use_rethrow_when_possible: true,
    use_string_in_part_of_directives: true,
    use_super_parameters: true,
    void_checks: true,
    depend_on_referenced_packages: true,
    package_names: true,
    secure_pubspec_urls: true,
    
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true